### ISSUE TITLE
Figure out IPC connection

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/open-archive-dweb-backend#14]
We need to lay the foundation for doing rpc between the backend and the frontend. One approach would be to make use of unix domain sockets to register a listener on the backend and send requests to it on the frontend.

## Phase 1: Rust unix domain registration

- make a new rust project with two files, a listener and a sender
- Use tokio's [UnixStream library](https://docs.rs/tokio/latest/tokio/net/struct.UnixStream.html)
- Have the listener listen on connections in a unix domain socket path passed in from the cli args (maybe a file in the current directory?)
- It should echo any data it gets on the connection back to the sender then close the connection
- Have the sender take the same path as a cli arg and send "Hello World" down the socket, then print the output to stdout

## Phase 2: Mobile connection

- embed the rust server as an FFI library in a mobile app with a function to start/stop it and take an argument for the socket path
- resolve some path for the socket in app-specific storage [android](https://medium.com/android-knowledge-store/android-unix-domain-socket-2cfec4a12ee7) [io](https://stackoverflow.com/a/56136361)
- Open the socket on the Kotlin/Swift (or whatever lang you prefer) and send "hello world" to the server
- Log the response back

## Phase 3: HTTP over unix domain socket

- Use the code [here](https://github.com/http-rs/tide/pull/531) to register an http server on the unix domain socket in the listener
- Register a single request listener that just responds to GET requests with `200` and `Hello World` in the body
- Update the rust sender to issue an http GET request to the domain socket [use this code as a hint for how](https://github.com/seanmonstar/reqwest/pull/1623)
- Update the ios/android code to make http requests over the socket too

**Comment by RangerMauve** [comment]
For android we might need to find an HTTP library which can be passed a socket instance or write a library ourselves :skull: 

https://stackoverflow.com/questions/10673684/send-http-request-manually-via-socket

**Comment by RangerMauve** [comment]
Worst case we can ditch http and do a custom protocol

**Comment by RangerMauve** [comment]
If the http path doesn't work out we could use protocol buffers with some adhoc rpc protocol. or maybe json rpc?

**Comment by RangerMauve** [comment]
https://github.com/apple/swift-protobuf

**Comment by RangerMauve** [comment]
Alternately we can use gRPC

https://github.com/grpc/grpc-swift

https://grpc.io/docs/languages/kotlin/

https://github.com/hyperium/tonic

**Comment by writerly03** [comment]
Phase 2 done: https://github.com/OpenArchive/save-android

**Comment by RangerMauve** [comment]
Richard ended up going with HTTP for part 2 anyway and just implemented the HTTP connection over sockets manually.
