### ISSUE TITLE
Create and publish Veilid groups

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/open-archive-dweb-backend#16]
Create groups and publish to veilid with name, read name from keypair

- [ ] create groups and publish to veilid with name, read name from keypair
- [ ] store a map of groups from their public key to a Box<Group> in the backend
- [ ] Create a routing context per group
- [ ] Inside create group create a new dht record, also use veilid crypto to generate a random encryption key
- [ ] Store dht record in Group
- [ ] Invoke set_name on group which will set subkey 0 to the string
- [ ] Have get_name read from subkey 0
- [ ] write a unit test to see that you can write then read the name
- [ ] Store group keypair/secret key in protected table store with the public key as the "key" and the data as the value. (in cbor using serde?)
- [ ] When loading the group by public key attempt to read from the store, error if not available
- [ ] Add method to load group from public key, encryption key, Option<private key> which will skip creating a new dht record, have the public key only api invoke this
- [ ] add method to close the group and unload the dht record / remove from the backend map
- [ ] write a test to see that we can load a group from storage after we closed it, and after we stopped the veilid node / started a new one
- [ ] Add encrypt and decrypt methods to the Group
- [ ] Encrypt the data before setting in set_name, decrypt in get_name, do so via the dht wrappers
- [ ] Ensure the get_name tests still work

**Comment by tripledoublev** [comment]
This is a lot. Curious if it would make sense to break down into smaller milestones.
Something like:
- Setting and getting group name
- Storing and loading group keypair
- Loading and closing groups
- Encrypting and decrypting data

**Comment by RangerMauve** [comment]
Sure, I was imagining we could have those subtasks grouped in here, but opening new issues would be good for being able to place on the roadmap more easily
