### ISSUE TITLE
Filecoin Foundation July update

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/open-archive-dweb-backend#17]

**Comment by writerly03** [comment]
@RangerMauve can you add some bullet points for this prompt:

in july, what progress was made? lessons learned?

**Comment by RangerMauve** [comment]
So far:

- June we finalized approach and tested core technologies
- updated roadmap and timeline with specific tasks
- settled on cryptographic system for data sharing and user privacy
- started on "backend daemon" implementation
- working with OA team on front end screens and connections to backend

**Comment by RangerMauve** [comment]
- got code for storing/loading groups and user data repos over veilid
- got tunnels over veilid to a point where we're testing reliability
- initial mockups of new screens for the UI
- starting on implementing inter-process-communication for the front and back end

**Comment by tripledoublev** [comment]
- implemented key storage and management for groups (keypair and encryption)
