### ISSUE TITLE
Track collection for data repo and add data to it, update DHT with hash

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/open-archive-dweb-backend#20]

**Comment by tripledoublev** [comment]
From Mauve:

> Here's the code for the app message. Store the route id blob on the dht at index 2 and add a method to the Repo to send an AppMessage to the repo owner by looking up this key. https://github.com/RangerMauve/veilid-examples-rs/blob/default/src/main.rs#L50

**Comment by RangerMauve** [comment]
We have infra for tracking the hash and tunnels, will need to start working on integrating the iroh stuff next

**Comment by RangerMauve** [comment]
I'm gonna focus on replication, in the meantime @tripledoublev can start adding collection tracking

- add the `initial` branch from my veilid iroh blobs repo as a dependency
- initialize the module inside the backend and make it available to groups/repos
- when creating a new group create a en empty iroh collection and set the root hash on the dht
- track the dht record info and collection CID inside the veilid store
- creating a repo for a group should check to see if it's created in the veilid store before 
- add an upload_file command which will take the file name, upload it, then add it to the collection with the file name as the key and update the dht with the new collection root

**Comment by RangerMauve** [comment]
https://github.com/RangerMauve/veilid-iroh-blobs/blob/initial/src/iroh.rs

**Comment by RangerMauve** [comment]
Working on collection management

**Comment by RangerMauve** [comment]
Replication logic:
0. get the hash of a blob
1. get route ID's for members in groups
2. ask members for who has the blob
3. from successful asks, randomly pick one
4. try to download the file
5. if it fails go to 1
6. after 3 fails give up and error

**Comment by tripledoublev** [comment]
all of the items listed are included in PR openarchive/save-dweb-backend#9
there is the exception of the collection piece which mauve is working on 

> - add the initial branch from my veilid iroh blobs repo as a dependency
> - initialize the module inside the backend and make it available to groups/repos
> - when creating a new group create a en empty iroh collection and set the root hash on the dht
> - track the dht record info and collection CID inside the veilid store
> - creating a repo for a group should check to see if it's created in the veilid store before
> - add an upload_file command which will take the file name, upload it, then add it to the collection with the file name as the key and update the dht with the new collection root

**Comment by RangerMauve** [comment]
Here's what we should do for collections:
- update [veilid-iroh-blobs](https://github.com/RangerMauve/veilid-iroh-blobs/blob/default/src/iroh.rs#L56)
- we should track collections via the "tags" feature in the iroh store
- collections should have an arbitrary ID (maybe add a prefix like `collection-{name}1 in the actual storage?
- Collection keys are file paths and values are blob hashes
- `create_collection(collectionName: string) -> Result<Hash>`
- `set_file(collectionName, path: string, hash) -> Result<Hash>` (return collection hash)
- `get_file(collectionName, path) -> Result<Hash>`
- `delete_file(collectionNAme, path) -> Result<Hash>` (return collection hash)
- `list_files(collectionNAme)  -> Result<Vec<string>>`
- `collection_hash(collectionName) -> Result<Hash>`
- `upload_to(collectionName, path, file stream)  -> Result<Hash>`, use upload file to ge the file hash, set in collection, return new c ollection hash

**Comment by RangerMauve** [comment]
Here's some more insights for the collection stuff:

- Storing collection: https://github.com/n0-computer/iroh/blob/main/iroh-blobs/src/format/collection.rs#L209
- Loading: https://github.com/n0-computer/iroh/blob/main/iroh-blobs/src/format/collection.rs#L188
- It implements iterator: https://github.com/n0-computer/iroh/blob/main/iroh-blobs/src/format/collection.rs#L58
- store.insert_many is how we get that root hash for the collection. https://github.com/n0-computer/iroh/blob/main/iroh-blobs/examples/provide-bytes.rs#L59

Should be able to modify a collection by modifying it's `.blobs` property

**Comment by RangerMauve** [comment]
Closing in favor of new issues
