### ISSUE TITLE
Standardize on ABI to invoke via FFI

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/open-archive-dweb-backend#21]
Part 1: now that rust server is embedded in the app, need to ake a hello world api call
write code on the front end that will establish requests
Also something on the back end

Part 2:
implement the different requests

**Comment by writerly03** [comment]
This needs the IPC to move ahead.

**Comment by RangerMauve** [comment]
Summary: we will use a variation of JSON-RPC over Unix Domain sockets.

The "front end" will open sockets to the "back end" then send requests as a single line of JSON. Optionally followed by binary data for file uploads. The backend will respond with a line of JSON optionally followed by binary data for file downloads.

Steps:
- Have JNI function for setting up rust server take two string arguments: `storageLocation` and `socketPAth`
- Have rust server listen on connections on the socket path
- FOr each new connection: Read a line (until `\n`), parse as [JSON](https://docs.rs/json/latest/json/), print to STDout, check for the "method" field and make a `match` statement. If `method` is `"hello"` respond with the JSON `{"result": "world"}`. If method isn't known write back a JSON blob that looks like this: `{"error": {"code": 404, "message": "Method not found ${method}"}}`

On the client side, have a class that takes a unix domaion socket path as an argument and exposes a method called `call(method: string, params: Option<JSONMap>) : JSONMap` which will open a unix socket to the given path, write the request as a line of JSON, read a line of JSON back, and return the `result` to the caller. Check for the `error` field and throw an error if it exists with the given `message`

Once these are in place add a buttom somewhere where the server will get initialized on load, then it will make calls to the backend when you click the button and log the response.

From here we can start stubbing out the backend RPC API as we connect it to the app.

**Comment by RangerMauve** [comment]
Next steps: Glue to the front end.

For each screen of the Dweb backend in the app we need to do the following:
- abstract the data needed to render the view (e.g. list of groups)
- hardcode the data as JSON to start and render the views as is
- once that is working, add a new route on the rust side of the dweb backend which returns this fake data
- have the native view fetch this data from the backend on load

You will also need to figure out where to spawn the backend. On Android I'd suggest putting it in a Service kinda like what I did for IPFS in [this project](https://github.com/AgregoreWeb/agregore-mobile/blob/default/patches/0001-AG-IPFS-Daemon.patch#L149), that way the view can bind to it and start it up and then the service can be garbage collected by the OS.

**Comment by RangerMauve** [comment]
Next API todo:

- [ ] listing repos in a group
- [ ] adding yourself to a group and setting name
- [ ] upload file to own repo
- [ ] list files in repo
- [ ] download file from repo
- [ ] get URL for group
- [ ] join group from URL

**Comment by writerly03** [comment]
@rapuckett can you also close off Issue #13 as you complete the above checklist?

**Comment by rapuckett** [comment]
Yes, will keep the issue up to date as work progresses. Thanks.

**Comment by RangerMauve** [comment]
Closing in favor of new issues
