### ISSUE TITLE
Standardize on URI scheme for linking to groups

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/open-archive-dweb-backend#22]
Extend URI scheme for also adding data repo keypair for migrating devices

**Comment by writerly03** [comment]
Mauve to provide instructions for this later in the week (ignore for now)

**Comment by RangerMauve** [comment]
So here's what we need to store in the URL:

- dht key
- encryption key
- owner public key
- owner secret key

I propose we do something along the line of magnet links like this:

save+dweb:?dht={dht}&enc={encryption}&pk={public key}&sk={secret key}

I think we should use hex encoding.

The front end of the app doesn't need to parse it, just needs to register the protocol handler and pass it to the backend

**Comment by writerly03** [comment]
Mauve has the proposal for the URI scheme; Richard need to register the above in the app so that the app launches when the link is clicked. 

Hypha will have their piece completed by EOD (Tuesday).
