### ISSUE TITLE
"Backup server" listening for RPC to start replicating groups

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/open-archive-dweb-backend#23]

**Comment by writerly03** [comment]
Will initially do the demo w/ out this.

**Comment by writerly03** [comment]
- Create backup server
- Then create a CLI to add the data to groups
- Then attach this to the front end

@tripledoublev to start this week

**Comment by tripledoublev** [comment]
@RangerMauve, should I create a new repository for this or create a separate module within the same repository?

**Comment by RangerMauve** [comment]
Lets do same repository and have the `main` library be able to run a command like `save-dweb-backend start-backup` to start the backup instance and get it's route ID

**Comment by tripledoublev** [comment]
Resharing `next steps` following the merge of #18


- create RPCClient from veilid and the descriptor (also have a way to get descriptor from url and veilid)
- high level apis on the client for joining group etc
- existing cLI methods should take a backend URL as an arg (maybe from env var as well?) and init an RPC client
- have new subcommand called "start" which starts the rpc service and logs the URL
- If no su6bcommand is provided log a help message with the command list

**Comment by tripledoublev** [comment]
> existing cLI methods should take a backend URL as an arg (maybe from env var as well?) and init an RPC client

Is this different than `rpc_addr`?

https://github.com/OpenArchive/save-dweb-backend/blob/40d042e4a5edd112d2d91279134d0a845732df3a/src/main.rs#L46C8-L53C10

**Comment by tripledoublev** [comment]
Closed after merging openarchive/save-dweb-backend#17
