### ISSUE TITLE
Announcement blog post

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/open-archive-dweb-backend#24]

**Comment by writerly03** [comment]
Suggested Outline

- overview of the collaboration; supported by FFDW
- why this work is important
- what it adds to Save and the archiving community
- link to DWeb principles ?
- About each org
- About the funder?

**Comment by foundscapes** [comment]
> Suggested Outline
> 
>     * overview of the collaboration; supported by FFDW
> 
>     * why this work is important
> 
>     * what it adds to Save and the archiving community
> 
>     * link to DWeb principles ?
> 
>     * About each org
> 
>     * About the funder?

- Discuss privacy ux work we're doing and why it's so important to threat model and use human rights centered design when building new technologies to protect everyone downstream

**Comment by writerly03** [comment]
Announcement draft is here: https://docs.google.com/document/d/1N1U5X8Z6Y3Wt80pEgGpc_6EuNo5-psoIxb7fWPzxww4/edit?tab=t.0#heading=h.u9f0t7oj3b6l
