### ISSUE TITLE
Tunnels

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/open-archive-dweb-backend#26]
add tunnel to own repo, send "ping" app_call to others

**Comment by RangerMauve** [comment]
PR: https://github.com/RangerMauve/veilid-iroh-blobs/pull/1

**Comment by writerly03** [comment]
This is compiling but have to restructure the test to run between two peers.

Have made more progress on Iroh replication.

**Comment by writerly03** [comment]
90% done but still working on the testing piece of this. Waiting for Veilid folks to see if they fix the issue

**Comment by writerly03** [comment]
Intializing multiple nodes and establishing tunnels
Still no connection between those but working
