### ISSUE TITLE
List all repos in a group - Frontend

### ISSUE THREAD

**Issue by upulw2020** [hyphacoop/open-archive-dweb-backend#32]
List all repos in a group
Add an icon which identifies which one we created(can_write)

**Comment by tripledoublev** [comment]
[groups-and-repos.txt](https://github.com/user-attachments/files/17384442/groups-and-repos.txt) logs

From Richard:

> Here's a log trace of the create groups & repos flow. Ignore the "got snowbird repos" line - that just means it's past a certain line in code, not that it's gotten actual repos.

**Comment by tripledoublev** [comment]
The bug that was preventing us from listing repos has been fixed !

**Comment by rapuckett** [comment]
Verified working well on front-end.
