### ISSUE TITLE
Fix GET repos endpoint

### ISSUE THREAD

**Issue by rapuckett** [hyphacoop/open-archive-dweb-backend#50]
Example request:
GET /api/groups/xDuKzk0qO4WIPl9AMAxbRw_ph1vYWvQAt6aS6JDj5zU/repos

Response:
Error set to GeneralError(message=Unexpected error: Unexpected JSON token at offset 0: Expected start of the object '{', but had '[' instead at path: $JSON input: [])

**Comment by tripledoublev** [comment]
We can try returning a JSON object instead of an array by wrapping the repo_ids 
OpenArchive/save-rust#7
