### ISSUE TITLE
Bugfix - Download error on loading file

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/open-archive-dweb-backend#52]

**Comment by tripledoublev** [comment]
@RangerMauve, I added the step to my test that returns the following error:

> AppError occurred: Failed to download file from peers: Cannot download hash. No other peers found

Here it is -> https://github.com/OpenArchive/save-rust/commit/894363d8d50a27f8e746aa33d7128e4d705128bf

**Comment by tripledoublev** [comment]
Context: this is when no other peers are present, running tests with only one backend

**Comment by RangerMauve** [comment]
Fixed in latest commit, needed to change the upload and download code a bit
