### ISSUE TITLE
Remove unnessary `/{media_id}` 

### ISSUE THREAD

**Issue by RangerMauve** [hyphacoop/open-archive-dweb-backend#53]
This line is unnecessary https://github.com/OpenArchive/save-rust/blob/main/src/media.rs#L18

- Put filename instead of media id
- Remove file name from  query

**Comment by tripledoublev** [comment]
https://github.com/OpenArchive/save-rust/pull/12 This PR removes /{media_id} and includes a test for upload, list and delete

**Comment by tripledoublev** [comment]
> This line is unnecessary https://github.com/OpenArchive/save-rust/blob/main/src/media.rs#L18

The delete file operation fails in the test if I remove L18 so I did not take it out
